---
title: "预测：方法与实践 0 引言"
output: html_document
---

## 引言
欢迎阅读我们的在线预测教材。

本书的目的是对预测方法进行全面的介绍，并让读者快速上手每一种预测方法。我们没有详细讨论每种方法背后的理论细节，但读者可以从每个章节最后的参考文献中找到这些细节。

本书适合三类读者：（1）在业界想做预测但没有受过该领域专业教育的人；（2）读商科的本科生；（3）MBA学生。在澳大利亚莫纳什大学我们将该书用作商学本科三年级的课程教材。

在大部分章节中，我们假设读者熟悉初级统计学以及高中代数。有几个章节需要矩阵知识，但我们已做了标记。

在每个章节的最后，我们给出了“扩展阅读”。一般情况下，读者可以从“扩展阅读”中所列教材中找到更深层次或更详细的细节。如果没有合适的教材，我们给出了期刊文章，以提供给读者更多的参考信息。

在整本书中我们使用R语言，我们打算让学生学习如何用R进行预测。R是免费的，而且几乎适用于任何操作系统。R不仅适用于预测，而且还是所有统计分析的绝佳工具。对于如何安装和使用R，请参见附录中的 使用R。

本书中的所有R示例都假设读者已通过 library(fpp2) 加载了CRAN上的 fpp2 包。加载 fpp2 包的同时也加载了几个其他包，包括forecast 和 ggplot2，以及本书中用到的所有数据。 fpp2 这个包需要8.0版本以上的 forecast 包以及2.0.0版本以上的ggplot2包。

本书中所有的图都基于ggplot2包，如果读者想学习怎么修改图形，或者绘制自己的与书中不同的ggplot2图形，请参考 ggplot2书 (Wickham, 2016)，或者 DataCamp 在线学习平台上的 ggplot2课程。

对应本书，也有一个 DataCamp课程，该课程讲授了章节2，3，7和8的一些思想，并简单介绍了章节9和章节11中的一些主题。

本书与其他预测教科书相比有以下几个鲜明特点：

本书是免费的，并可以在线阅读，这使本书受众更广。
本书使用R，R是免费的、开源的、极其强大的软件。
本书的在线版本会持续更新。读者不需要等到下一版书的出版就可以看到书中的错误被纠正或者书中讨论了新的方法，因为我们将频繁在线更新本书。
本书展示了许多真实数据示例，这些都是从我们自己的咨询实践中获取的资源。我们已与上百家企业合作帮助他们解决预测问题，这些经验直接促成了这里给出的许多例子，并指导了我们的预测理念。
我们比大部分预测者更强调图形方法。我们通过图形来探索数据、分析模型的有效性并展示预测结果。
